#!/bin/bash
#
# Copyright (C) 2025 Matthew Wette
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, see <http://www.gnu.org/licenses/>.
#
#

# guild compile dummy1.scm
# ./convgo dummy1.go

cflags=$(pkg-config --cflags guile-3.0)
alibs=$(pkg-config --libs guile-3.0)
lflags=""
slibs=""
dlibs=""

function get_stuff () {
  while [ -n "$*" ]; do
    case $1 in
    -L*) lflags="$lflags $1 -Wl,-rpath=$(echo $1 | sed -e s/^..//)"; shift ;;
    -lguile*) slibs="$dlibs $1"; shift ;;
    *) dlibs="$dlibs $1"; shift ;;
    esac
  done
}

get_stuff $alibs

docase=6
set -x
case $docase in
1)
    echo gcc -g -o xguile xguile.c xo.d/*.xo \
	`pkg-config --cflags --libs guile-3.0`
    ;;
2)
    # fails
    gcc -g -o xguile xguile.c xo.d/*.xo \
	-static `pkg-config --cflags --libs guile-3.0`
    ;;
3)
    # fails
    gcc -g -o xguile xguile.c xo.d/*.xo \
	$cflags $lflags -static $slibs -shared $dlibs
    ;;
4)
    gcc -g -o xguile xguile.c xo.d/*.xo \
	$cflags $lflags $slibs $dlibs
    ;;
5)
    gcc -g -o xguile xguile.c xo.d/*.xo \
	$cflags $lflags /opt/local/lib/libguile-3.0.a $dlibs
    ;;
6)
    root=/opt/guile-rel/3.0.9-fzr
    gcc -g -o xguile xguile.c xo.d/*.xo \
	-I$root/include/guile/3.0 -L$root/lib -L/opt/local/lib \
	-lguile-3.0 $dlibs
    ;;
esac
   

# --- last line ---
