#!/bin/bash

# guild compile dummy1.scm
# ./convgo dummy1.go

docase=1
case $docase in
1)
    gcc -g -o xguile xguile.c xo.d/*.xo \
	`pkg-config --cflags --libs guile-3.0`
    ;;
2)
    gcc -g -o xguile xguile.c xo.d/*.xo \
	-static `pkg-config --cflags --libs guile-3.0`
    ;;
esac
   

# --- last line ---
