#!/bin/bash
#
# find in 
# -t TOPDIR  set topdir to find go file

topdir=$(guile -c "(display (assq-ref %guile-build-info 'ccachedir))")
output=
while test -n "$*"; do
    case $1 in
    -t) shift; topdir=$1 ;;
    -o) shift; output=$1 ;;
    *) gopath=$1 ;;
    esac
    shift
done
if test -n "$output"; then
    echo output=$output
    xofile=$output
else
    xofile=$(echo $gopath | sed -e 's/-/_/g' -e 's/\//_/g' -e 's/go$/xo/')
fi
xofile=$(realpath $xofile)

cd $topdir
objcopy -I binary -B i386 -O elf64-x86-64 \
	--add-section .note.GNU-stack=/dev/null \
		$gopath $xofile

# --- last line ---
